Repository IAA-CSIC/MUTIS, pull requests merged in 2021-06, with the labels that each got.

#18 Fix OU_fit and *_ab_p, *_ab methods, add lc_gen_psd_c to signal generation methods, add Signal().plot(), update OU_check_gen and gen_times_canopy, add docstrings.
  .gitignore
  docs/recipes/PSD_tests.ipynb
  docs/recipes/mutis_workflow.ipynb
  docs/recipes/sin_tests.ipynb
  docs/recipes/stochastics_tests.ipynb
  mutis/__init__.py
  mutis/correlation.py
  mutis/lib/correlation.py
  mutis/lib/signal.py
  mutis/lib/utils.py
  mutis/signal.py
Labels: bug, cleaning

#14 Add tests and improve test coverage
  mutis/correlation.py
  mutis/lib/correlation.py
  mutis/lib/signal.py
  mutis/signal.py
  mutis/tests/test_correlation.py
  mutis/tests/test_signal.py
Labels: infrastructure

#21 Add uncertainties to correlations
  docs/recipes/mutis_workflow.ipynb
  mutis/correlation.py
  mutis/lib/correlation.py
  mutis/signal.py
  mutis/tests/test_correlation.py
  mutis/tests/test_signal.py
Labels: enhancement
